apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: final-project
type: Opaque
stringData:
  POSTGRES_DB: bookstore
  POSTGRES_USER: bookstore
  POSTGRES_PASSWORD: bookstore123